version: "2"

services:
  apache:
    build:
      context: .
      dockerfile: apache/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - ftp_proxy
        - no_proxy
    image: ecmwf/uwsgitest-apache
    ports:
      - "8080:8080"
    links:
      - django
    read_only: true

  django:
    build:
      context: .
      dockerfile: django/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - ftp_proxy
        - no_proxy
    image: ecmwf/uwsgitest-django
    expose:
      - "3000"
    volumes:
      - ./django/docker-entrypoint.sh:/docker-entrypoint.sh:ro
    read_only: true
